packages:
  - "common-types"
  - "common-api"
  - "common-antd"
  - "common-react"
  - "common-config"
  - "common-util"
  - "common-dev"
  - "dateme-manage"
  - "dateme-app"
  - "dbtool"
  - "react-admin"
