server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  datasource:
#    url: jdbc:postgresql://localhost:5432/test?currentSchema=public&characterEncoding=utf8
#    url: jdbc:h2:mem:testdb
    url: jdbc:sqlite:test.sqlite
#    driver-class-name: org.h2.Driver
    driver-class-name: org.sqlite.JDBC
    username: test
    password: test
  threads:
    virtual:
      enabled: true
  application:
    name: dateme-server
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    generate-ddl: false
    show-sql: true
#    open-in-view: false
logging:
  level:
    web: debug