server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=public&characterEncoding=utf8
    username: test
    password: test
  threads:
    virtual:
      enabled: true
  application:
    name: dateme-server
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    open-in-view: false