javax:
  sql:
    DataSource:
      test:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dataSource.url: jdbc:h2:mem:unit-testing;DB_CLOSE_DELAY=-1
        dataSource.user: sa
        dataSource.password: sa