[package]
name = "dbcli-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
postgres = "0.19.7"
ratatui = "0.26.1"
